db.mongo.local=false
db.mongo.uri=mongodb://unifi:unifipass@unifi-db:27017/unifi?authSource=admin
statdb.mongo.uri=mongodb://unifi:unifipass@unifi-db:27017/unifi_stat?authSource=admin
unifi.db.name=unifi