#!/bin/sh
# /etc/uci-defaults/99-set-hostname
if [ -f /sys/firmware/devicetree/base/chosen/rootdisk-nvme ]; then
    hostname="BPI-R4-NVMe"
elif grep -q 'ubi' /proc/cmdline; then
    hostname="BPI-R4-NAND"
elif [ -f /sys/firmware/devicetree/base/chosen/rootdisk-emmc ]; then
    hostname="BPI-R4-eMMC"
elif [ -f /sys/firmware/devicetree/base/chosen/rootdisk-sd ]; then
    hostname="BPI-R4-SD"
else
    hostname="BPI-R4"
fi
uci set system.@system[0].hostname="$hostname"
uci commit system